spec_version: 1
name: ai-prompt-builder
services:
  - name: web
    github:
      repo: kongsungeui/claude-prompt-manager
      branch: main
    source_dir: /
    run_command: gunicorn app:app -b 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    build_command: pip install -r requirements.txt
    instance_count: 1
    instance_size_slug: basic-xxs
    http_check:
      path: /
      protocol: HTTP
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
      - key: CLAUDE_API_KEY
        scope: RUN_AND_BUILD_TIME
